### ISSUE TITLE
Link minimal dependencies

### ISSUE THREAD

**Issue by f6cd** [KDAB/KDGpu#2]
Hello. Thank you for open-sourcing this library, the API is neat and I've enjoyed experimenting with it so far.
In creating a minimal project with CMake on Windows I linked just the `KDGpu` target - yet noticed it dragged in DLLs for `GLM`, `libKDGpuKDGui`, `libKDGui`, `libKDFoundation`, and `libKDUtils` . This is much more code than I wanted!

A few things:
* It appears that the `assets` and `KDGpuExample` targets are built, even when `KDGPU_BUILD_EXAMPLES` is disabled - meaning we're always downloading+building `GLM`, `STB`, and `Imgui`, and trying to copy fonts+textures.
* The defunct `TOYRENDERER_BUILD_TESTS` define is used in `dependencies.cmake`.
* `KDUtils` is only used twice; for bitflags (could probably be dropped directly into this repo) and the `readShaderFile` method (file IO is arguably out-of-scope for a graphics abstraction).
* An option to disable the `KDGpuKDGui` layer.
* `KDFoundation` is only used for `KDExample` and `KDGpuKDGui`; it should be excluded if you choose to build neither.

These are superficial changes - however it seems like this repo is a mirror of some internal repo, so you don't take PRs? Hopefully documenting this is sufficient..

**Comment by seanharmer** [comment]
Hi and thanks for taking the time to try out KDGpu and send this feedback. Yes at present this is a mirror of an internal repo. That is just a convenience for now and we will switch it over completely to github in the future (hopefully near future).

I'll look at getting these build system issues sorted out and pushed.

**Comment by seanharmer** [comment]
KDGpu itself now only links to spdlog (could make this optional later) and VMA.

If you configure with the KDGPU_BUILD_TESTS and KDGPU_BUILD_EXAMPLES options off, then it should no longer fetchcontent for KDUtils and only build the KDGpu library itself.
